Revert "build: install multiple Python versions for autosynth runs (#641)" (#646)
This reverts commit 2a29860e484695a07aa8670f9e750bfeeb308a43.

It broke the build for all Python synth jobs.  Here's the log:

```
Downloading Python-3.7.7.tar.xz...
-> https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tar.xz
Installing Python-3.7.7...
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (Ubuntu 14.04 using python-build 1.2.19-1-gece59ca8)
```