chore(python): update .kokoro/requirements.txt (#1569)
The release script failed in [this log](https://fusion2.corp.google.com/invocations/0688d329-b69a-4d07-8bea-e011a1993478/log) with 

```
Collecting jaraco.classes
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    jaraco.classes from [https://files.pythonhosted.org/packages/8f/e6/f92d21f915cee7acf1cfe3e0ec60b8e9888dcf40a9814e3838a87ba487d0/jaraco.classes-3.2.2-py3-none-any.whl#sha256=e6ef6fd3fcf4579a7a019d87d1e56a883f4e4c35cfe925f86731abc58804e647](https://www.google.com/url?q=https://files.pythonhosted.org/packages/8f/e6/f92d21f915cee7acf1cfe3e0ec60b8e9888dcf40a9814e3838a87ba487d0/jaraco.classes-3.2.2-py3-none-any.whl%23sha256%3De6ef6fd3fcf4579a7a019d87d1e56a883f4e4c35cfe925f86731abc58804e647&sa=D) (from keyring==23.9.0->-r github/python-bigquery-data-exchange/.kokoro/requirements.txt (line 254))
```

I believe the issue is that the requirements.txt file is out of date and doesn't include `jaraco.classes`